### ISSUE TITLE
Erreur pour le docker-compose de l'api gateway

### ISSUE THREAD

**Issue by jade243** [hostettler/microservices#4]
Lorsque j'exécute:
`sudo docker-compose -f docker-compose-api-gw.yml up`

J'obtiens l'erreur suivante:
```
ERROR: for api-gateway-init  Container "8653205d5ad3" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

J'ai donc mis en commentaire api-gateway-init dans le .yml et j'ai l'erreur suivante:
```
iam              | 19:17:30,887 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (ServerService Thread Pool -- 60) ERROR: duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"
iam              |   Detail: Key (realm_id, username)=(master, admin) already exists.
iam              | 19:17:30,906 ERROR [org.keycloak.services] (ServerService Thread Pool -- 60) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
```

Est-ce que vous avez la solution ?

**Comment by hostettler** [comment]
I have the same error, this is "normal". It is due to the fact that we reload the configuration. I get the same but it ends with 
`iam                 | 11:41:31,357 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management

iam                 | 11:41:31,357 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990

iam                 | 11:41:31,358 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 4.8.3.Final (WildFly Core 6.0.2.Final) started in 41315ms - Started 670 of 930 services (649 services are lazy, passive or on-demand)`

**Comment by jade243** [comment]
Ok thanks, I found a solution for the unhealthy container, I added 
`kong migrations finish &` at the beginning of api-gateway command. It seems to work.
